apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vr44jfbcy-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6ecc9b13b8.cen7.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:cc4ca480f2c3eb081674d03c2bc1f6371e571baf@sha256:9d3c64e96c7ec3fd3cdb9cc7cf410004a839a728b9e7f988f77dd994282b5057
          name: container-image
